### ISSUE TITLE
This module is not AOT compliant

### ISSUE THREAD

**Issue by paynoattn** [Tixifni/ngx-localforage#7]
Hello,

Thank you for developing this module! I love localforage and I love angular2.

I was getting an error when trying to build my app using AOT:
```Uncaught Error: Unexpected value 'undefined' imported by the module 'LocalForageModule'```

I believe these are caused by the ```export * from``` in the barrel files. See [here](https://blog.angularindepth.com/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5) for why.

I've managed to fix this, will be pushing a pull request soon.

**Comment by paynoattn** [comment]
I've also noticed that the linter fails during development, specifically in the LocalForageService using the ```let``` keyword and then never reassigning the variable.

Additionally, there are several violations I've noticed in the [angular styleguide](https://github.com/johnpapa/angular-styleguide).

I'll be submitting a pull request shortly.

**Comment by paynoattn** [comment]
@radyz @Xepe Is this repository dead? I can make my own npm package and maintain it if it is.

**Comment by Xepe** [comment]
Hello @paynoattn, 
Thanks for report the issue. 

No it is not dead, I will try to review the issue this night. 

Thanks.

**Comment by paynoattn** [comment]
Awesome, there is already a PR #8.

**Comment by paynoattn** [comment]
@Xepe any progress?

**Comment by paynoattn** [comment]
Looks like my PR was merged, are we going to merge to master and deploy?

**Comment by Xepe** [comment]
Hello @paynoattn, 

It is in master with version 0.1.35 

Thanks for all.
Regards.
